spring:
  application:
    name: Exchange
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

server:
  servlet:
    context-path: /exchange
  port: 8080

fx:
  api-url: https://api.ratesapi.io/api/latest

springdoc:
  swagger-ui:
      path: /api-docs.html

